export enum TechnologiesEnum {
  Title = "My Technologies",
  React = "React",
  Redux = "Redux",
  Javascript = "Javascript",
  HTML = "HTML",
  Express = "Express",
  NestJS = "NestJS",
  Github = "Github",
  CSS = "CSS",
  NodeJS = "NodeJS",
  Apollo = "Apollo",
  GraphQL = "GraphQL",
  Typescript = "Typescript",
  NextJS = "NextJS",
  StyledComponent = "Styled Component",
  MaterialUI = "Material UI",
  Solidity = "Solidity",
  Mongo = "Mongo",
  Gatsby = "Gatsby",
  RXJS = "RXJS",
}
